### ISSUE TITLE
VLC Media Player - URL

### ISSUE THREAD

**Issue by citrixguyblog** [haavarstein/Applications#1]
The download of the VLC installer is not working anymore.
Script Output: http://get.videolan.org/vlc/3.0.6/win64/vlc-3.0.6-win64.exe

New location: https://ftp.fau.de/videolan/vlc/3.0.6/win64/vlc-3.0.6-win64.exe

Just replace the variable $url with the following:
**$url = "https://ftp.fau.de/videolan/vlc/$($Version)/win64/vlc-$($Version)-win64.exe"**

**Comment by haavarstein** [comment]
Fixed, thanks
